version: '3.1'

services:
  postgres:
    image: postgis/postgis
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432

  maildev:
    image: maildev/maildev
    environment:
      - MAILDEV_WEB_PORT=1080
      - MAILDEV_SMTP_PORT=1025
      - MAILDEV_INCOMING_USER=${MAIL_USER}
      - MAILDEV_INCOMING_PASS=${MAIL_PASSWORD}
    ports:
      - "8082:1080"
      - "8025:1025"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
